/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-4DA.h
 #	source generated by 4D Plugin Wizard
 #	Project : 4DA Opener
 #	author : miyako
 #	2023/01/13
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_4DA_H
#define PLUGIN_4DA_H

#include "4DPluginAPI.h"
#include "4DPlugin-JSON.h"

#pragma mark -

static void Clone_structure_file(PA_PluginParameters params);

#endif /* PLUGIN_4DA_H */
